import type { Farm, MarketPrice } from './types';

export const farms: Farm[] = [
  {
    id: 'farm-001',
    name: "Green Valley Organics",
    location: "Nashik, Maharashtra",
    soilType: "Loam",
    ph: 6.8,
    moisture: 35,
    nutrients: {
      nitrogen: 120,
      phosphorus: 50,
      potassium: 80,
    },
  },
  {
    id: 'farm-002',
    name: "Sunrise Meadows",
    location: "Ludhiana, Punjab",
    soilType: "Silty Clay",
    ph: 7.2,
    moisture: 45,
    nutrients: {
      nitrogen: 150,
      phosphorus: 65,
      potassium: 100,
    },
  },
  {
    id: 'farm-003',
    name: "Golden Plains",
    location: "Anantapur, Andhra Pradesh",
    soilType: "Sandy Loam",
    ph: 6.5,
    moisture: 25,
    nutrients: {
      nitrogen: 100,
      phosphorus: 40,
      potassium: 70,
    },
  },
];

export const indianCities: string[] = [
    "Mumbai, Maharashtra",
    "Delhi, Delhi",
    "Bengaluru, Karnataka",
    "Ahmedabad, Gujarat",
    "Hyderabad, Telangana",
    "Chennai, Tamil Nadu",
    "Kolkata, West Bengal",
    "Pune, Maharashtra",
    "Jaipur, Rajasthan",
    "Surat, Gujarat",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Nagpur, Maharashtra",
    "Indore, Madhya Pradesh",
    "Thane, Maharashtra",
    "Bhopal, Madhya Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Pimpri-Chinchwad, Maharashtra",
    "Patna, Bihar",
    "Vadodara, Gujarat",
    "Ghaziabad, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Agra, Uttar Pradesh",
    "Nashik, Maharashtra",
    "Faridabad, Haryana",
    "Meerut, Uttar Pradesh",
    "Rajkot, Gujarat",
    "Kalyan-Dombivali, Maharashtra",
    "Vasai-Virar, Maharashtra",
    "Varanasi, Uttar Pradesh",
    "Srinagar, Jammu and Kashmir",
    "Aurangabad, Maharashtra",
    "Dhanbad, Jharkhand",
    "Amritsar, Punjab",
    "Navi Mumbai, Maharashtra",
    "Allahabad, Uttar Pradesh",
    "Ranchi, Jharkhand",
    "Howrah, West Bengal",
    "Coimbatore, Tamil Nadu",
    "Jabalpur, Madhya Pradesh",
    "Gwalior, Madhya Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Jodhpur, Rajasthan",
    "Madurai, Tamil Nadu",
    "Raipur, Chhattisgarh",
    "Kota, Rajasthan",
    "Guwahati, Assam",
    "Chandigarh, Chandigarh",
    "Solapur, Maharashtra",
    "Hubli-Dharwad, Karnataka",
    "Bareilly, Uttar Pradesh",
    "Moradabad, Uttar Pradesh",
    "Mysore, Karnataka",
    "Gurgaon, Haryana",
    "Aligarh, Uttar Pradesh",
    "Jalandhar, Punjab",
    "Tiruchirappalli, Tamil Nadu",
    "Bhubaneswar, Odisha",
    "Salem, Tamil Nadu",
    "Mira-Bhayandar, Maharashtra",
    "Thiruvananthapuram, Kerala",
    "Bhiwandi, Maharashtra",
    "Saharanpur, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Guntur, Andhra Pradesh",
    "Bikaner, Rajasthan",
    "Amravati, Maharashtra",
    "Noida, Uttar Pradesh",
    "Jamshedpur, Jharkhand",
    "Bhilai, Chhattisgarh",
    "Cuttack, Odisha",
    "Firozabad, Uttar Pradesh",
    "Kochi, Kerala",
    "Nellore, Andhra Pradesh",
    "Bhavnagar, Gujarat",
    "Dehradun, Uttarakhand",
    "Durgapur, West Bengal",
    "Asansol, West Bengal",
    "Rourkela, Odisha",
    "Nanded, Maharashtra",
    "Kolhapur, Maharashtra",
    "Ajmer, Rajasthan",
    "Akola, Maharashtra",
    "Gulbarga, Karnataka",
    "Jamnagar, Gujarat",
    "Ujjain, Madhya Pradesh",
    "Loni, Uttar Pradesh",
    "Siliguri, West Bengal",
    "Jhansi, Uttar Pradesh",
    "Ulhasnagar, Maharashtra",
    "Jammu, Jammu and Kashmir",
    "Sangli-Miraj & Kupwad, Maharashtra",
    "Mangalore, Karnataka",
    "Erode, Tamil Nadu",
    "Belgaum, Karnataka",
    "Ambattur, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Malegaon, Maharashtra",
    "Gaya, Bihar",
    "Tiruppur, Tamil Nadu",
    "Davanagere, Karnataka",
    "Kozhikode, Kerala",
    "Kurnool, Andhra Pradesh",
    "Udaipur, Rajasthan",
    "Bokaro, Jharkhand",
    "Bellary, Karnataka",
    "Rajahmundry, Andhra Pradesh",
    "Gopalpur, West Bengal",
    "Agartala, Tripura",
    "Bhagalpur, Bihar",
    "Muzaffarnagar, Uttar Pradesh",
    "Bhatpara, West Bengal",
    "Panihati, West Bengal",
    "Latur, Maharashtra",
    "Dhule, Maharashtra",
    "Rohtak, Haryana",
    "Korba, Chhattisgarh",
    "Bhilwara, Rajasthan",
    "Brahmapur, Odisha",
    "Muzaffarpur, Bihar",
    "Ahmednagar, Maharashtra",
    "Mathura, Uttar Pradesh",
    "Kollam, Kerala",
    "Avadi, Tamil Nadu",
    "Kadapa, Andhra Pradesh",
    "Kamarhati, West Bengal",
    "Sambalpur, Odisha",
    "Bilaspur, Chhattisgarh",
    "Shahjahanpur, Uttar Pradesh",
    "Satara, Maharashtra",
    "Thrissur, Kerala",
    "Alwar, Rajasthan",
    "Kakinada, Andhra Pradesh",
    "Puducherry, Puducherry",
    "Shimla, Himachal Pradesh",
    "Imphal, Manipur",
    "Aizawl, Mizoram",
    "Shillong, Meghalaya",
    "Gangtok, Sikkim",
    "Panaji, Goa",
    "Anantapur, Andhra Pradesh"
];

export const marketPrices: MarketPrice[] = [
    { 
        crop: 'Corn', 
        price: 1400, 
        change: 50, 
        lastUpdated: '2h ago',
        history: [
            { date: 'Jan', price: 1380 },
            { date: 'Feb', price: 1410 },
            { date: 'Mar', price: 1400 },
            { date: 'Apr', price: 1430 },
            { date: 'May', price: 1460 },
            { date: 'Jun', price: 1400 },
        ]
    },
    { 
        crop: 'Soybeans', 
        price: 3500, 
        change: -120, 
        lastUpdated: '1h ago',
        history: [
            { date: 'Jan', price: 3450 },
            { date: 'Feb', price: 3580 },
            { date: 'Mar', price: 3520 },
            { date: 'Apr', price: 3510 },
            { date: 'May', price: 3550 },
            { date: 'Jun', price: 3500 },
        ]
    },
    { 
        crop: 'Wheat', 
        price: 2200, 
        change: 250, 
        lastUpdated: '3h ago',
        history: [
            { date: 'Jan', price: 2100 },
            { date: 'Feb', price: 2150 },
            { date: 'Mar', price: 2190 },
            { date: 'Apr', price: 2210 },
            { date: 'May', price: 2180 },
            { date: 'Jun', price: 2200 },
        ]
    },
    { 
        crop: 'Grapes', 
        price: 80, 
        change: 2, 
        lastUpdated: '4h ago',
        history: [
            { date: 'Jan', price: 78 },
            { date: 'Feb', price: 79 },
            { date: 'Mar', price: 81 },
            { date: 'Apr', price: 82 },
            { date: 'May', price: 83 },
            { date: 'Jun', price: 80 },
        ]
     },
    { 
        crop: 'Lettuce', 
        price: 45, 
        change: -5, 
        lastUpdated: '1h ago',
        history: [
            { date: 'Jan', price: 42 },
            { date: 'Feb', price: 43 },
            { date: 'Mar', price: 46 },
            { date: 'Apr', price: 48 },
            { date: 'May', price: 47 },
            { date: 'Jun', price: 45 },
        ]
    },
];
